# Generated by Django 3.0.2 on 2020-02-19 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singer', models.CharField(max_length=100)),
                ('album', models.CharField(max_length=100)),
                ('release', models.DateField(default='')),
                ('hashtag', models.DecimalField(decimal_places=0, max_digits=10)),
                ('song', models.CharField(max_length=100)),
                ('lyrics', models.TextField(default='')),
            ],
        ),
    ]
