# Generated by Django 3.0.2 on 2020-02-19 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='album',
            field=models.CharField(max_length=100, verbose_name='專輯'),
        ),
        migrations.AlterField(
            model_name='music',
            name='hashtag',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='順序'),
        ),
        migrations.AlterField(
            model_name='music',
            name='lyrics',
            field=models.TextField(default='可不填', verbose_name='歌詞'),
        ),
        migrations.AlterField(
            model_name='music',
            name='release',
            field=models.DateField(default='', verbose_name='專輯發行年分'),
        ),
        migrations.AlterField(
            model_name='music',
            name='singer',
            field=models.CharField(max_length=100, verbose_name='歌手'),
        ),
        migrations.AlterField(
            model_name='music',
            name='song',
            field=models.CharField(max_length=100, verbose_name='歌名'),
        ),
    ]
